CREATE OR REPLACE PROCEDURE "BACKUP_H_SMS_CONCAT_S"(
    NUMBER_OF_DAYS IN NUMBER := 7 )
AS
  CURSOR CAMPAIGNS
  IS
    SELECT CAMPAIGN_ID FROM ADM_CAMPAIGNS;
  newTableName VARCHAR2(30);
RUN_ID NUMBER;
BEGIN
 SELECT H_SP_EXEC_TIME_RUN_SEQ.nextval INTO RUN_ID FROM dual;
 LOG_H_SP_EXEC_TIME(RUN_ID, 'BACKUP_H_SMS_CONCAT_S', systimestamp, null);
  newTableName := 'H_SMS_CONCAT_S_ARC';
 EXECUTE IMMEDIATE 'INSERT /*+APPEND*/ INTO '||newTableName||' SELECT * FROM H_SMS_CONCAT_S WHERE TRUNC(SENDING_TIME) < TRUNC( sysdate - '''||NUMBER_OF_DAYS||''')';
 DELETE FROM H_SMS_CONCAT_S WHERE TRUNC(SENDING_TIME) < TRUNC( sysdate - NUMBER_OF_DAYS);
 COMMIT;     
 LOG_H_SP_EXEC_TIME(RUN_ID, 'BACKUP_H_SMS_CONCAT_S', null, systimestamp);
END;