CREATE OR REPLACE PROCEDURE "BACKUP_PROCESS_INFO"(
    v_retention IN NUMBER )
AS
  RUN_ID NUMBER;
BEGIN
  SELECT H_SP_EXEC_TIME_RUN_SEQ.nextval INTO RUN_ID FROM dual;
  LOG_H_SP_EXEC_TIME(RUN_ID, 'BACKUP_PROCESS_INFO', systimestamp, NULL);
  INSERT /*+APPEND*/
  INTO ADM_PROCESS_INFO_ARCHIVE
  SELECT * FROM ADM_PROCESS_INFO WHERE ENTRY_DATE <= TRUNC(sysdate-v_retention);
  COMMIT;
  DELETE FROM ADM_PROCESS_INFO WHERE ENTRY_DATE <= TRUNC(sysdate-v_retention);
  EXECUTE IMMEDIATE 'COMMIT';
  LOG_H_SP_EXEC_TIME(RUN_ID, 'BACKUP_PROCESS_INFO', NULL, systimestamp);
END;