CREATE TABLE H_SMS_CONCAT_S_ARC 
   (	CAMPAIGN_ID VARCHAR2(255 BYTE), 
	CONCAT_SEQUENCE VARCHAR2(255 BYTE), 
	MESSAGE_TEXT VARCHAR2(255 BYTE), 
	MSG_ID VARCHAR2(255 BYTE), 
	MSISDN VARCHAR2(255 BYTE), 
	MSISDN_MOD_X VARCHAR2(255 BYTE), 
	SMSC_SESSION_IDENTIFIER VARCHAR2(255 BYTE), 
	STATUS NUMBER, 
	CONCAT_COUNT NUMBER, 
	SENDING_TIME DATE
   );
   
   CREATE INDEX "CONCAT_SEQ_IDX_ARC" ON H_SMS_CONCAT_S_ARC(CONCAT_SEQUENCE DESC)