  CREATE TABLE "H_SP_EXEC_TIME_LOGS" 
   (	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SP_NAME" VARCHAR2(35 BYTE), 
	"START_TIME" TIMESTAMP,
  "FINISH_TIME" TIMESTAMP
   );
   
   CREATE SEQUENCE  "H_SP_EXEC_TIME_RUN_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE ;
