create or replace PROCEDURE "IMMEDIATE_BACKUP_H_SMS_CON_S" AS
historyDate varchar2(30);
newTableName varchar2(30);
RUN_ID NUMBER;
BEGIN
 SELECT H_SP_EXEC_TIME_RUN_SEQ.nextval INTO RUN_ID FROM dual;
 LOG_H_SP_EXEC_TIME(RUN_ID, 'IMMEDIATE_BACKUP_H_SMS_CON_S', systimestamp, null);

newTableName := 'H_SMS_CONCAT_S_ARC';
EXECUTE IMMEDIATE 'ALTER TABLE H_SMS_CONCAT_S RENAME TO '|| newtablename;
EXECUTE IMMEDIATE 'CREATE TABLE H_SMS_CONCAT_S 
   (	CAMPAIGN_ID VARCHAR2(255 BYTE), 
	CONCAT_SEQUENCE VARCHAR2(255 BYTE), 
	MESSAGE_TEXT VARCHAR2(255 BYTE), 
	MSG_ID VARCHAR2(255 BYTE), 
	MSISDN VARCHAR2(255 BYTE), 
	MSISDN_MOD_X VARCHAR2(255 BYTE), 
	SMSC_SESSION_IDENTIFIER VARCHAR2(255 BYTE), 
	STATUS NUMBER, 
	CONCAT_COUNT NUMBER, 
	SENDING_TIME DATE
   )';
   
EXECUTE IMMEDIATE 'ALTER INDEX CONCAT_SEQ_IDX RENAME TO CONCAT_SEQ_IDX_ARC';

EXECUTE IMMEDIATE 'CREATE INDEX "CONCAT_SEQ_IDX" ON H_SMS_CONCAT_S(CONCAT_SEQUENCE DESC)';
   
 LOG_H_SP_EXEC_TIME(RUN_ID, 'IMMEDIATE_BACKUP_H_SMS_CON_S', null, systimestamp);
END;