create or replace PROCEDURE "IMMEDIATE_BACKUP_H_SMS" AS
historyDate varchar2(30);
newTableName varchar2(30);
RUN_ID NUMBER;
BEGIN
 SELECT H_SP_EXEC_TIME_RUN_SEQ.nextval INTO RUN_ID FROM dual;
 LOG_H_SP_EXEC_TIME(RUN_ID, 'IMMEDIATE_BACKUP_H_SMS', systimestamp, null);
historyDate := TO_CHAR(sysdate,'yyyymmdd');-- can be replaced with '20200101' for a specific date.
newTableName := 'H_SMS'||historyDate;
EXECUTE IMMEDIATE 'ALTER TABLE H_SMS RENAME TO '|| newtablename;
EXECUTE IMMEDIATE 'CREATE TABLE H_SMS
(
  H_ID NUMBER(*,0) NOT NULL ENABLE, 
	MSISDN CHAR(20 CHAR), 
	MSISD_PART_DIGIT NUMBER, 
	SMS_TEXT VARCHAR2(3000 BYTE), 
	NOTIFICATION_ID NUMBER(*,0), 
	CAMPAIGN_ID NUMBER(*,0), 
	ENTRY_DATE TIMESTAMP (6), 
	HISTORY_DATE DATE, 
	STATUS NUMBER, 
	MSG_ID VARCHAR2(255 BYTE), 
	APP_PROFILE_ID NUMBER, 
	SMS_JSON VARCHAR2(4000 BYTE), 
	CONCAT_COUNT NUMBER, 
	DELIVERED_COUNT NUMBER, 
	DESCRIPTION VARCHAR2(255 BYTE), 
	PROCESS_ID NUMBER(38,0)
)
PARTITION BY RANGE (CAMPAIGN_ID)
INTERVAL(1)
SUBPARTITION BY LIST (MSISD_PART_DIGIT)
SUBPARTITION TEMPLATE
  (SUBPARTITION SUB_0 VALUES (''0''),
   SUBPARTITION SUB_1 VALUES (''1''),
   SUBPARTITION SUB_2 VALUES (''2''),
   SUBPARTITION SUB_3 VALUES (''3''),
   SUBPARTITION SUB_4 VALUES (''4''),
   SUBPARTITION SUB_5 VALUES (''5''),
   SUBPARTITION SUB_6 VALUES (''6''),
   SUBPARTITION SUB_7 VALUES (''7''),
   SUBPARTITION SUB_8 VALUES (''8''),
   SUBPARTITION SUB_9 VALUES (''9'')
  )
(PARTITION INVALID VALUES LESS THAN (0)
(SUBPARTITION INVALID_SUB_0 VALUES (''0''),
   SUBPARTITION INVALID_SUB_1 VALUES (''1''),
   SUBPARTITION INVALID_SUB_2 VALUES (''2''),
   SUBPARTITION INVALID_SUB_3 VALUES (''3''),
   SUBPARTITION INVALID_SUB_4 VALUES (''4''),
   SUBPARTITION INVALID_SUB_5 VALUES (''5''),
   SUBPARTITION INVALID_SUB_6 VALUES (''6''),
   SUBPARTITION INVALID_SUB_7 VALUES (''7''),
   SUBPARTITION INVALID_SUB_8 VALUES (''8''),
   SUBPARTITION INVALID_SUB_9 VALUES (''9'')
   )
)';
EXECUTE IMMEDIATE 'ALTER INDEX HSMS_MSG_ID_IDX RENAME TO HSMS_MSG_ID_IDX'||historyDate;

EXECUTE IMMEDIATE 'CREATE INDEX HSMS_MSG_ID_IDX ON H_SMS (MSG_ID) LOCAL NOPARALLEL';

 LOG_H_SP_EXEC_TIME(RUN_ID, 'IMMEDIATE_BACKUP_H_SMS', null, systimestamp);
END;