
Insert into ADM_SYSTEM_PROPERTIES (GROUP_ID,ITEM_ID,GROUP_NAME,ITEM_VALUE,ENTRY_KEY,DESCRIPTION) values (65,25,'NBA Integration','application/json','TIPCO_ACCEPT_HEADER','TIPCO accept header');
Insert into ADM_SYSTEM_PROPERTIES (GROUP_ID,ITEM_ID,GROUP_NAME,ITEM_VALUE,ENTRY_KEY,DESCRIPTION) values (65,26,'NBA Integration','application/json','TIPCO_CONTENT_TYPE_HEADER','TIPCO content type header');
Insert into ADM_SYSTEM_PROPERTIES (GROUP_ID,ITEM_ID,GROUP_NAME,ITEM_VALUE,ENTRY_KEY,DESCRIPTION) values (65,27,'NBA Integration','CCAT','TIPCO_X_SOURCE_SYSTEM_HEADER','TIPCO x source system header');
Insert into ADM_SYSTEM_PROPERTIES (GROUP_ID,ITEM_ID,GROUP_NAME,ITEM_VALUE,ENTRY_KEY,DESCRIPTION) values (65,28,'NBA Integration','ccat','TIPCO_X_SOURCE_IDENTITY_TOKEN_HEADER','TIPCO x source identity token header');
Insert into ADM_SYSTEM_PROPERTIES (GROUP_ID,ITEM_ID,GROUP_NAME,ITEM_VALUE,ENTRY_KEY,DESCRIPTION) values (65,29,'NBA Integration','en','TIPCO_ACCEPT_LANGUAGE_HEADER','TIPCO accept language header');
