-- DML for inserting ADM_SYSTEM_PROPERTIES
INSERT INTO ADM_SYSTEM_PROPERTIES (GROUP_ID, ITEM_ID, GROUP_NAME, ITEM_VALUE, ENTRY_KEY, DESCRIPTION) 
VALUES ('33', '7', 'Prepaid VBP', 'false', 'RETRIEVE_SP_DATA_FROM_VBP', 'Retrieve sp data from vbp flag');
