
 CREATE TABLE "TX_LOGIN_FP" 
   (	"TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"NT_ACCOUNT" VARCHAR2(200 BYTE), 
	"MACHINE_NAME" VARCHAR2(200 BYTE), 
	"DOMAIN_NAME" VARCHAR2(200 BYTE)
   ) PARTITION BY RANGE (TIMESTAMP)
INTERVAL(NUMTODSINTERVAL(1,'DAY'))
(PARTITION INVALID VALUES LESS THAN (TIMESTAMP'2018-01-01 00:00:00'));

  
  
