RENAME B2B_OTF_DIAL_INFO TO B2B_OTF_DIAL_INFO20191231;
  CREATE TABLE "B2B_OTF_DIAL_INFO" 
   (	"CAMPAIGN_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PARAMETERS" VARCHAR2(160 BYTE), 
	"MSISDN_LAST_DIG" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BATCH_ID" NUMBER, 
	"START_FROM" DATE, 
	"ORDER_ID" NUMBER DEFAULT "B2B_OTF_DIAL_INFO_ORDER_SEQ"."NEXTVAL" NOT NULL ENABLE,
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"PROCESS_ID" NUMBER(38,0)
   )  
  PARTITION BY RANGE ("CAMPAIGN_ID") INTERVAL (1) 
  SUBPARTITION BY LIST ("MSISDN_LAST_DIG") 
  SUBPARTITION TEMPLATE ( 
    SUBPARTITION "SUB_00" VALUES ( '0' ), 
    SUBPARTITION "SUB_01" VALUES ( '1' ), 
    SUBPARTITION "SUB_02" VALUES ( '2' ), 
    SUBPARTITION "SUB_03" VALUES ( '3' ), 
    SUBPARTITION "SUB_04" VALUES ( '4' ), 
    SUBPARTITION "SUB_05" VALUES ( '5' ), 
    SUBPARTITION "SUB_06" VALUES ( '6' ), 
    SUBPARTITION "SUB_07" VALUES ( '7' ), 
    SUBPARTITION "SUB_08" VALUES ( '8' ), 
    SUBPARTITION "SUB_09" VALUES ( '9' )) 
 (PARTITION "INVALID"  VALUES LESS THAN (0) );
 
 
  RENAME GROUP_MSISDN TO GROUP_MSISDN20191231;
  CREATE TABLE "GROUP_MSISDN" 
   (	"GROUP_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"MSISDN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PARAMETERS" VARCHAR2(160 BYTE), 
	"MSISDN_LAST_DIG" VARCHAR2(20 BYTE) NOT NULL ENABLE
   ) 
  PARTITION BY RANGE ("GROUP_ID") INTERVAL (1) 
  SUBPARTITION BY LIST ("MSISDN_LAST_DIG") 
  SUBPARTITION TEMPLATE (  
    SUBPARTITION "SUB_00" VALUES ( '0' ), 
    SUBPARTITION "SUB_01" VALUES ( '1' ), 
    SUBPARTITION "SUB_02" VALUES ( '2' ), 
    SUBPARTITION "SUB_03" VALUES ( '3' ), 
    SUBPARTITION "SUB_04" VALUES ( '4' ), 
    SUBPARTITION "SUB_05" VALUES ( '5' ), 
    SUBPARTITION "SUB_06" VALUES ( '6' ), 
    SUBPARTITION "SUB_07" VALUES ( '7' ), 
    SUBPARTITION "SUB_08" VALUES ( '8' ), 
    SUBPARTITION "SUB_09" VALUES ( '9' )) 
 (PARTITION "INVALID"  VALUES LESS THAN (0) );


 INSERT INTO GROUP_MSISDN (GROUP_ID,
		MSISDN,
		PARAMETERS,
		MSISDN_LAST_DIG) select GROUP_ID,
		MSISDN,
		PARAMETERS,
 SUBSTR(MSISDN,11,11) from GROUP_MSISDN20191231;

UPDATE ADM_SYSTEM_PROPERTIES set VALUE='2000' where KEY ='DIALS_BATCH_SIZE';

create or replace PROCEDURE "GET_OTF_CAMPAIGN_DIALS" (
   P_CAMPAIGN_ID            NUMBER,
   P_LAST_DIGIT   VARCHAR2,
   P_DIALS              OUT SYS_REFCURSOR)
AS
   V_BATCH_ID   NUMBER;
   V_BATCH_SIZE   NUMBER;
   
/*
Retrieve Batchs of MSISDNS to be served for running campaigns.
CREATED BY Mohamed Abdelaty
STATUS
   [0]       -> SUCCESS
   [-1]      -> NO RECRODS
  [-100]   -> UNHANDLED EXCEPTION
*/
BEGIN
    -- Get unique batch id from sequence 
   V_BATCH_ID := OTF_BATCH_ID_SEQ.NEXTVAL;

  select VALUE into V_BATCH_SIZE from ADM_SYSTEM_PROPERTIES where KEY = 'DIALS_BATCH_SIZE';
    --MARK CURRENT BATCH TO BE DEQUEUED
   UPDATE B2B_OTF_DIAL_INFO
      SET BATCH_ID = V_BATCH_ID
    WHERE CAMPAIGN_ID = P_CAMPAIGN_ID 
      AND MSISDN_LAST_DIG = P_LAST_DIGIT 
      AND BATCH_ID IS NULL
      AND TRUNC(START_FROM) < TRUNC(SYSDATE + 1)
      AND ROWNUM <= V_BATCH_SIZE;

   COMMIT;

   OPEN P_DIALS FOR
      SELECT *
        FROM B2B_OTF_DIAL_INFO DIALS
       WHERE CAMPAIGN_ID = P_CAMPAIGN_ID 
      AND MSISDN_LAST_DIG = P_LAST_DIGIT 
      AND DIALS.BATCH_ID = V_BATCH_ID;

EXCEPTION
   WHEN OTHERS
   THEN
      LOG_SP_EXCEPTION('GET_OTF_CAMPAIGN_DIALS('|| P_CAMPAIGN_ID || ')', SQLCODE, SQLERRM);
      RAISE;
END;

RENAME H_SMS TO H_SMS20191231;
CREATE TABLE H_SMS
(
  H_ID              INTEGER                     NOT NULL,
  MSISDN            CHAR(20 CHAR),
  MSISD_PART_DIGIT  NUMBER,
  SMS_TEXT          VARCHAR2(3000 BYTE),
  NOTIFICATION_ID   INTEGER,
  CAMPAIGN_ID       INTEGER,
  ENTRY_DATE        TIMESTAMP(6),
  HISTORY_DATE      DATE,
  STATUS            NUMBER,
  MSG_ID            VARCHAR2(255 BYTE),
  APP_PROFILE_ID    NUMBER,
  SMS_JSON          VARCHAR2(4000 BYTE),
  CONCAT_COUNT      NUMBER,
  DELIVERED_COUNT   NUMBER,
  DESCRIPTION       VARCHAR2(255 BYTE),
  PROCESS_ID        NUMBER(38)
)
PARTITION BY RANGE (CAMPAIGN_ID)
INTERVAL( 1)
SUBPARTITION BY LIST (MSISD_PART_DIGIT)
SUBPARTITION TEMPLATE
  (SUBPARTITION PART_0 VALUES ('0'),
   SUBPARTITION PART_1 VALUES ('1'),
   SUBPARTITION PART_2 VALUES ('2'),
   SUBPARTITION PART_3 VALUES ('3'),
   SUBPARTITION PART_4 VALUES ('4'),
   SUBPARTITION PART_5 VALUES ('5'),
   SUBPARTITION PART_6 VALUES ('6'),
   SUBPARTITION PART_7 VALUES ('7'),
   SUBPARTITION PART_8 VALUES ('8'),
   SUBPARTITION PART_9 VALUES ('9')
  )
(PARTITION INVALID VALUES LESS THAN (0));

 INSERT INTO H_SMS (H_ID,
  MSISDN,
  MSISD_PART_DIGIT  ,
  SMS_TEXT          ,
  NOTIFICATION_ID   ,
  CAMPAIGN_ID       ,
  ENTRY_DATE        ,
  HISTORY_DATE      ,
  STATUS            ,
  MSG_ID            ,
  APP_PROFILE_ID   	,
  SMS_JSON          ,
  CONCAT_COUNT      ,
  DELIVERED_COUNT   ,
  DESCRIPTION       ,
  PROCESS_ID    ) select H_ID,
		MSISDN,
		SUBSTR(MSISDN,11,11),
		SMS_TEXT          ,
  NOTIFICATION_ID   ,
  CAMPAIGN_ID       ,
  ENTRY_DATE        ,
  HISTORY_DATE      ,
  STATUS            ,
  MSG_ID            ,
  APP_PROFILE_ID   	,
  SMS_JSON          ,
  CONCAT_COUNT      ,
  DELIVERED_COUNT   ,
  DESCRIPTION       ,
  PROCESS_ID from H_SMS20191231;